use skrifa::instance::{LocationRef, Size};
use skrifa::outline::{DrawSettings, OutlinePen};
use skrifa::{FontRef, GlyphId, MetadataProvider};
use std::fmt::Write;

#[derive(Debug)]
enum Cmd {
    MoveTo(i16, i16),
    LineTo(i16, i16),
    QuadTo(i16, i16, i16, i16),
    CubicTo(i16, i16, i16, i16, i16, i16),
    Close,
}

struct Extractor {
    commands: Vec<Cmd>,
    largest_coordinate: i16,
    cubic_segments: usize,
}

impl Extractor {
    fn coordinate(&mut self, value: f32) -> i16 {
        self.largest_coordinate = self.largest_coordinate.max(value.abs().ceil() as i16);
        let value = value * 2.0;
        assert_eq!(
            value.fract(),
            0.0,
            "outline coordinate was not half-integral: {value}"
        );
        assert!(
            value >= i16::MIN as f32 && value <= i16::MAX as f32,
            "outline coordinate did not fit i16: {value}"
        );
        let value = value.round() as i16;
        value
    }
}

impl OutlinePen for Extractor {
    fn move_to(&mut self, x: f32, y: f32) {
        let (x, y) = (self.coordinate(x), self.coordinate(y));
        self.commands.push(Cmd::MoveTo(x, y));
    }

    fn line_to(&mut self, x: f32, y: f32) {
        let (x, y) = (self.coordinate(x), self.coordinate(y));
        self.commands.push(Cmd::LineTo(x, y));
    }

    fn quad_to(&mut self, cx: f32, cy: f32, x: f32, y: f32) {
        let (cx, cy, x, y) = (
            self.coordinate(cx),
            self.coordinate(cy),
            self.coordinate(x),
            self.coordinate(y),
        );
        self.commands.push(Cmd::QuadTo(cx, cy, x, y));
    }

    fn curve_to(&mut self, cx0: f32, cy0: f32, cx1: f32, cy1: f32, x: f32, y: f32) {
        let (cx0, cy0, cx1, cy1, x, y) = (
            self.coordinate(cx0),
            self.coordinate(cy0),
            self.coordinate(cx1),
            self.coordinate(cy1),
            self.coordinate(x),
            self.coordinate(y),
        );
        self.cubic_segments += 1;
        self.commands.push(Cmd::CubicTo(cx0, cy0, cx1, cy1, x, y));
    }

    fn close(&mut self) {
        self.commands.push(Cmd::Close);
    }
}

fn emit_cmd(out: &mut String, command: &Cmd) {
    match command {
        Cmd::MoveTo(x, y) => writeln!(out, "    Cmd::MoveTo({x}, {y}),").unwrap(),
        Cmd::LineTo(x, y) => writeln!(out, "    Cmd::LineTo({x}, {y}),").unwrap(),
        Cmd::QuadTo(cx, cy, x, y) => writeln!(out, "    Cmd::QuadTo({cx}, {cy}, {x}, {y}),").unwrap(),
        Cmd::CubicTo(cx0, cy0, cx1, cy1, x, y) => writeln!(out, "    Cmd::CubicTo({cx0}, {cy0}, {cx1}, {cy1}, {x}, {y}),").unwrap(),
        Cmd::Close => writeln!(out, "    Cmd::Close,").unwrap(),
    }
}

fn emit_glyph(out: &mut String, name: &str, advance: i16, commands: &[Cmd]) {
    if commands.is_empty() {
        writeln!(out, "const {name}_OUTLINE: &[Cmd] = &[];").unwrap();
    } else {
        writeln!(out, "const {name}_OUTLINE: &[Cmd] = &[").unwrap();
        for command in commands {
            emit_cmd(out, command);
        }
        writeln!(out, "];").unwrap();
    }
    writeln!(out, "pub const {name}: Glyph = Glyph {{\n    advance: {advance},\n    outline: {name}_OUTLINE,\n}};\n").unwrap();
}

fn main() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let output_path = std::env::args_os()
        .nth(1)
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| root.join("src/render/indicator/glyphs.rs"));
    let font_bytes = std::fs::read(root.join("fonts/LiberationSans-Regular.ttf")).unwrap();
    let font = FontRef::new(&font_bytes).unwrap();
    let units_per_em = font.metrics(Size::unscaled(), LocationRef::default()).units_per_em * 2;
    let charmap = font.charmap();
    let metrics = font.glyph_metrics(Size::unscaled(), LocationRef::default());
    let outlines = font.outline_glyphs();
    let mut output = String::from("// Generated by scripts/gen-glyphs from fonts/LiberationSans-Regular.ttf. Do not edit by hand.\n\n");
    output.push_str("pub const UNITS_PER_EM: u16 = ");
    writeln!(output, "{units_per_em};\n").unwrap();
    output.push_str("#[derive(Clone, Copy)]\n#[allow(dead_code)]\npub enum Cmd {\n    MoveTo(i16, i16),\n    LineTo(i16, i16),\n    QuadTo(i16, i16, i16, i16),\n    CubicTo(i16, i16, i16, i16, i16, i16),\n    Close,\n}\n\n#[derive(Clone, Copy)]\npub struct Glyph {\n    pub advance: i16,\n    pub outline: &'static [Cmd],\n}\n\n");

    let mut largest_coordinate = 0;
    let mut cubic_segments = 0;
    let mut glyphs = Vec::new();
    let codepoints = (0x20..=0x7e)
        .chain(0xa0..=0x17f)
        .chain(0x384..=0x3ce)
        .chain(0x400..=0x45f)
        .chain(0x2010..=0x2027);
    for c in codepoints.map(|code| char::from_u32(code).unwrap()) {
        let Some(glyph_id) = charmap.map(c) else { continue };
        let advance = metrics.advance_width(glyph_id).unwrap() * 2.0;
        assert_eq!(advance.fract(), 0.0, "advance was not half-integral: {advance}");
        assert!(
            advance >= i16::MIN as f32 && advance <= i16::MAX as f32,
            "advance did not fit i16: {advance}"
        );
        let advance = advance.round() as i16;
        let mut extractor = Extractor { commands: Vec::new(), largest_coordinate: 0, cubic_segments: 0 };
        outlines.get(glyph_id).unwrap().draw(DrawSettings::unhinted(Size::unscaled(), LocationRef::default()), &mut extractor).unwrap();
        largest_coordinate = largest_coordinate.max(extractor.largest_coordinate);
        cubic_segments += extractor.cubic_segments;
        glyphs.push((c, advance, extractor.commands));
    }
    let mut notdef = Extractor { commands: Vec::new(), largest_coordinate: 0, cubic_segments: 0 };
    let notdef_id = GlyphId::NOTDEF;
    outlines.get(notdef_id).unwrap().draw(DrawSettings::unhinted(Size::unscaled(), LocationRef::default()), &mut notdef).unwrap();
    largest_coordinate = largest_coordinate.max(notdef.largest_coordinate);
    cubic_segments += notdef.cubic_segments;
    let notdef_advance = metrics.advance_width(notdef_id).unwrap() * 2.0;
    assert_eq!(notdef_advance.fract(), 0.0);
    assert!(notdef_advance >= i16::MIN as f32 && notdef_advance <= i16::MAX as f32);
    emit_glyph(&mut output, "NOTDEF", notdef_advance.round() as i16, &notdef.commands);
    for (index, (_, advance, commands)) in glyphs.iter().enumerate() {
        emit_glyph(&mut output, &format!("GLYPH_{index}"), *advance, commands);
    }
    output.push_str("pub static GLYPHS: &[(char, Glyph)] = &[\n");
    for (index, (c, _, _)) in glyphs.iter().enumerate() {
        writeln!(output, "    ('\\u{{{:x}}}', GLYPH_{index}),", *c as u32).unwrap();
    }
    output.push_str("];\n\npub fn lookup(c: char) -> Option<&'static Glyph> {\n    GLYPHS\n        .binary_search_by_key(&c, |(character, _)| *character)\n        .ok()\n        .map(|index| &GLYPHS[index].1)\n}\n");
    std::fs::write(output_path, output).unwrap();
    eprintln!("glyphs: {}, largest absolute coordinate: {largest_coordinate}, cubic segments: {cubic_segments}", glyphs.len());
}
